apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-{{port}}
  namespace: addons-mysql-{{port}}
  labels:
    app.kubernetes.io/name: mysql-{{port}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-{{port}}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-{{port}}
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-{{port}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: tcp-mysql-{{port}}
        volumeMounts:
        - name: mysql-{{port}}-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-{{port}}-storage
        persistentVolumeClaim:
          claimName: mysql-{{port}}-claim