apiVersion: v1
kind: Service
metadata:
  name: sqlserver-{{port}}
  namespace: addons-sqlserver-{{port}}
  labels:
    app.kubernetes.io/name: sqlserver-{{port}}
spec:
  type: NodePort
  ports:
    - name: sqlserver-{{port}}
      port: {{port}}
      targetPort: sqlserver-{{port}}
      nodePort: {{node}}
  selector:
    app.kubernetes.io/name: sqlserver-{{port}}