apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-{{port}}-claim
  namespace: addons-magento-{{port}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: magento-{{port}}-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-mariadb-{{port}}-claim
  namespace: addons-magento-{{port}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: magento-mariadb-{{port}}-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-es-{{port}}-claim
  namespace: addons-magento-{{port}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: magento-es-{{port}}-storage
  resources:
    requests:
      storage: 10Gi