apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: magento-{{port}}
  namespace: addons-magento-{{port}}
  labels:
    app.kubernetes.io/name: magento-{{port}}
spec:
  serviceName: magento-{{port}}
  selector:
    matchLabels:
      app.kubernetes.io/name: magento-{{port}}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: magento-{{port}}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: magento-{{port}}
        image: bitnami/magento:latest
        imagePullPolicy: "Always"
        env:
        - name: MAGENTO_USERNAME
          value: user
        - name: MAGENTO_PASSWORD
          value: password
        - name: MAGENTO_DATABASE_HOST
          value: 127.0.0.1
        - name: MAGENTO_DATABASE_PORT_NUMBER
          value: "3306"
        - name: MAGENTO_DATABASE_NAME
          value: magento
        - name: MAGENTO_DATABASE_USER
          value: admin
        - name: MAGENTO_DATABASE_PASSWORD
          value: password
        - name: MAGENTO_ELASTICSEARCH_HOST
          value: 127.0.0.1
        ports:
          - name: magento-{{port}}
            containerPort: 8080
        volumeMounts:
        - mountPath: /bitnami/magento
          name: magento-{{port}}-storage
          
      - name: mariadb-{{port}}
        image: mariadb:latest
        imagePullPolicy: "Always"
        env:
        - name: MARIADB_USER
          value: admin
        - name: MARIADB_PASSWORD
          value: password
        - name: MARIADB_ROOT_PASSWORD
          value: password
        - name: MARIADB_DATABASE
          value: magento
        ports:
          - name: m-mariadb-{{port}}
            containerPort: 3306
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: magento-mariadb-{{port}}-storage
      
      - name: es-{{port}}
        image: bitnami/elasticsearch:latest
        imagePullPolicy: "Always"
        ports:
          - name: m-es-{{port}}
            containerPort: 9200
        volumeMounts:
        - mountPath: /bitnami/elasticsearch
          name: magento-es-{{port}}-storage
          
      volumes:
      - name: magento-{{port}}-storage
        persistentVolumeClaim:
          claimName: magento-{{port}}-claim
      - name: magento-mariadb-{{port}}-storage
        persistentVolumeClaim:
          claimName: magento-mariadb-{{port}}-claim
      - name: magento-es-{{port}}-storage
        persistentVolumeClaim:
          claimName: magento-es-{{port}}-claim
          