apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magento-{{port}}-storage
  namespace: addons-magento-{{port}}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magento-{{port}}-pv
  namespace: addons-magento-{{port}}
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: magento-{{port}}-storage
  local:
    path: {{path}}/magento
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magento-mariadb-{{port}}-storage
  namespace: addons-magento-{{port}}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magento-mariadb-{{port}}-pv
  namespace: addons-magento-{{port}}
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: magento-mariadb-{{port}}-storage
  local:
    path: {{path}}/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magento-es-{{port}}-storage
  namespace: addons-magento-{{port}}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magento-es-{{port}}-pv
  namespace: addons-magento-{{port}}
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: magento-es-{{port}}-storage
  local:
    path: {{path}}/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
