apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rules-{{port}}-claim
  namespace: addons-rules-{{port}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rules-{{port}}-storage
  resources:
    requests:
      storage: 5Gi
