apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{port}}
  namespace: addons-mongodb-{{port}}
  labels:
    app.kubernetes.io/name: mongodb-{{port}}
spec:
  type: NodePort
  ports:
    - name: mongodb-{{port}}
      port: {{port}}
      targetPort: mongodb-{{port}}
      nodePort: {{node}}
  selector:
    app.kubernetes.io/name: mongodb-{{port}}
---
apiVersion: v1
kind: Service
metadata:
  name: express-{{port}}
  namespace: addons-mongodb-{{port}}
  labels:
    app.kubernetes.io/name: express-{{port}}
spec:
  type: NodePort
  ports:
    - name: express-{{port}}
      port: 8081
      targetPort: express-{{port}}
  selector:
    app.kubernetes.io/name: mongodb-{{port}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-{{port}}-ingress
  namespace: addons-mongodb-{{port}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /addons/mongo
        backend:
          service:
            name: express-{{port}}
            port: 
              number: 8081