apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap-{{port}}
  namespace: addons-openldap-{{port}}
  labels:
    app.kubernetes.io/name: openldap-{{port}}
spec:
  serviceName: openldap-{{port}}
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap-{{port}}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap-{{port}}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: openldap-{{port}}
        image: docker.io/bitnami/openldap:2.5.11
        imagePullPolicy: "Always"
        env:
        - name: LDAP_ADMIN_USERNAME
          value: "admin"
        - name: LDAP_ADMIN_PASSWORD
          value: "password"
        - name: LDAP_USERS
          value: "user01,user02,user{{port}}"
        - name: LDAP_PASSWORDS
          value: "password01,password02,password{{port}}"
        ports:
        - name: tcp-ldap-{{port}}
          containerPort: 1389
        volumeMounts:
        - mountPath: /bitnami/openldap
          name: openldap-storage
      volumes:
      - name: openldap-storage
        hostPath:
          path: {{path}}
          type: DirectoryOrCreate