apiVersion: v1
kind: Service
metadata:
  name: demo-cart-{{port}}
  namespace: addons-demo-cart-{{port}}
  labels:
    app.kubernetes.io/name: demo-cart-{{port}}
spec:
  type: NodePort
  ports:
    - name: demo-cart-{{port}}
      port: {{port}}
      targetPort: demo-cart-{{port}}
      nodePort: {{node}}
  selector:
    app.kubernetes.io/name: demo-cart-{{port}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-cart-{{port}}-ingress
  namespace: addons-demo-cart-{{port}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /addons/demo/cart
        backend:
          service:
            name: demo-cart-{{port}}
            port: 
              number: 3000