apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{name}}
  labels:
    app: {{name}}
  namespace: dcp-{{name}}
spec:
  serviceName: {{name}}
  selector:
    matchLabels:
      app: {{name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: dcp-{{name}}-storage
          persistentVolumeClaim:
            claimName: dcp-{{name}}-claim
        - name: dcp-pg-{{name}}-storage
          persistentVolumeClaim:
            claimName: dcp-pg-{{name}}-claim
      containers:
      - image: boomi/dcp-catalog:latest
        securityContext:
          runAsUser: 1000
        imagePullPolicy: IfNotPresent
        name: dcp-{{name}}-node
        env:
        - name: DCP_VERSION
          value: "4.11"
        - name: DCP_DOT_VERSION
          value: "4.11"
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "1000m"
            memory: "8Gi"
          requests:
            cpu: "1000m"
            memory: "8Gi"
        volumeMounts:
        - name: dcp-{{name}}-storage
          mountPath: /usr/local/unifing-catalog-4.11
      - image: postgres:12.5
        name: dcp-pg-{{name}}
        env:
        - name: POSTGRES_PASSWORD
          value: unifi
        - name: POSTGRES_USER
          value: unifi
        - name: POSTGRES_DB
          value: invalid
        ports:
        - containerPort: 5432
          name: dcp-pg-{{name}}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dcp-pg-{{name}}-storage
      - image: cassandra:3.11.10
        name: dcp-ca-{{name}}
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: MAX_HEAP_SIZE
            value: 1024M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_LISTEN_ADDRESS
            value: "127.0.0.1"
          - name: CASSANDRA_SEEDS
            value: "127.0.0.1"
          - name: CASSANDRA_CLUSTER_NAME
            value: "DCP"
          - name: CASSANDRA_DC
            value: "DC1-DCP"
          - name: CASSANDRA_RACK
            value: "Rack1-DCP"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql