apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{name}}
  labels:
    app: {{name}}
  namespace: dcp-{{name}}
spec:
  serviceName: {{name}}
  selector:
    matchLabels:
      app: {{name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      terminationGracePeriodSeconds: 60
      #volumes:
      #  - name: dcp-{{name}}-storage
      #    persistentVolumeClaim:
      #      claimName: dcp-{{name}}-claim
      containers:
      - image: boomi/dcp-catalog:latest
        imagePullPolicy: IfNotPresent
        name: dcp-{{name}}-node
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "1000m"
            memory: "7680Mi"
          requests:
            cpu: "1000m"
            memory: "7680Mi"
        #volumeMounts:
        #  - name: dcp-{{name}}-storage
        #    mountPath: /usr/local/Unifi
        env:
        - name: DCP_VERSION
          value: "4.11"
        - name: DCP_DOT_VERSION
          value: "4.11"