apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}
  namespace: dcp-{{name}}
spec:
  type: ClusterIP
  selector:
    app: {{name}}
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{name}}-pg
  labels:
    app: {{name}}-pg
  namespace: dcp-{{name}}
spec:
  type: ClusterIP
  selector:
    app: {{name}}-pg
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{name}}-ingress-api
  namespace: dcp-{{name}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^([^.?]*[^/])$ $1/ redirect;
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /datai
        backend:
          service:
            name: {{name}}
            port: 
              number: 8000
      - pathType: Prefix
        path: /datai-api
        backend:
          service:
            name: {{name}}
            port: 
              number: 8000
      - pathType: Prefix
        path: /static
        backend:
          service:
            name: {{name}}
            port: 
              number: 8000