apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}
  namespace: molecule-{{name}}
spec:
  selector:
    app: {{name}}
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: {{port}}
    targetPort: 80
