apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}
  namespace: molecule-{{name}}
spec:
  selector:
    app: {{name}}
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    nodePort: {{port}}
    port: 9090
    targetPort: 9090
