apiVersion: v1
kind: Service
metadata:
  name: vault-{{port}}
  namespace: addons-vault-{{port}}
  labels:
    app.kubernetes.io/name: vault-{{port}}
spec:
  type: NodePort
  ports:
    - name: vault-{{port}}
      port: {{port}}
      targetPort: vault-{{port}}
      nodePort: {{node}}
  selector:
    app.kubernetes.io/name: vault-{{port}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-{{port}}-ingress
  namespace: addons-vault-{{port}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /ui
        backend:
          service:
            name: vault-{{port}}
            port: 
              number: 8200
      - pathType: Prefix
        path: /v1
        backend:
          service:
            name: vault-{{port}}
            port: 
              number: 8200