apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-{{port}}-storage
  namespace: addons-postgres-{{port}}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-{{port}}-pv
  namespace: addons-postgres-{{port}}
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres-{{port}}-storage
  local:
    path: {{path}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
