apiVersion: v1
kind: Service
metadata:
  name: sftp-{{port}}
  namespace: addons-sftp-{{port}}
  labels:
    app.kubernetes.io/name: sftp-{{port}}
spec:
  type: NodePort
  ports:
    - name: sftp-{{port}}
      port: {{port}}
      targetPort: sftp-{{port}}
      nodePort: {{node}}
  selector:
    app.kubernetes.io/name: sftp-{{port}}