apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracledb-{{port}}
  namespace: addons-oracledb-{{port}}
  labels:
    app.kubernetes.io/name: oracledb-{{port}}
spec:
  serviceName: oracledb-{{port}}
  selector:
    matchLabels:
      app.kubernetes.io/name: oracledb-{{port}}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oracledb-{{port}}
    spec:
      securityContext:
        runAsUser: 54321
        fsGroup: 1000
      containers:
      - image: gvenzl/oracle-xe:21.3.0
        name: oracledb-{{port}}
        env:
        - name: ORACLE_PASSWORD
          value: Password123!
        ports:
        - containerPort: 1521
          name: oracledb-{{port}}
        volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: oracledb-{{port}}-storage
      volumes:
      - name: oracledb-{{port}}-storage
        hostPath:
          path: {{path}}
          type: DirectoryOrCreate
