apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracledb-{{port}}
  namespace: addons-oracledb-{{port}}
  labels:
    app.kubernetes.io/name: oracledb-{{port}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oracledb-{{port}}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oracledb-{{port}}
    spec:
      containers:
      - image: store/oracle/database-enterprise:12.2.0.1
        name: oracledb-{{port}}
        ports:
        - containerPort: 1521
          name: oracledb-{{port}}
