apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracledb-{{port}}
  namespace: addons-oracledb-{{port}}
  labels:
    app.kubernetes.io/name: oracledb-{{port}}
spec:
  serviceName: oracledb-{{port}}
  selector:
    matchLabels:
      app.kubernetes.io/name: oracledb-{{port}}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oracledb-{{port}}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - image: store/oracle/database-enterprise:12.2.0.1
        name: oracledb-{{port}}
        ports:
        - containerPort: 1521
          name: oracledb-{{port}}
        volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: oracledb-{{port}}-storage
      volumes:
      - name: oracledb-{{port}}-storage
        persistentVolumeClaim:
          claimName: oracledb-{{port}}-claim
